<header>
        <div class="header_title_wrapper">
            <a href="index.html">
                <img src="images/node_logo.webp" class="header_logo" alt="node logo">
            </a>
            <h1 class="header_title">Node.JS</h1>
        </div>

        <nav class="top_navigation">
            <a href="index.html">Home</a>
            <a href="topic.html">Topic</a>
            <a href="quiz.html">Quiz</a>
            <a href="enhancements.html">Enchancements</a>
        </nav>

        <div class="link_wrapper">
            <a href="https://github.com/DannyOCE/inquiry-project">
                <img src="images/github_logo.png" class="github_logo" alt="github logo">
            </a>
        </div>
</header>