
<header>
        <div class="header_title_wrapper">
            <a href="index.php">
                <img src="images/node_logo.webp" class="header_logo" alt="node logo">
            </a>
            <h1 class="header_title">Node.JS</h1>
        </div>

        <nav class="top_navigation">
            <a href="index.php">Home</a>
            <a href="topic.php">Topic</a>
            <a href="enhancements.php">Enchancements</a>
            <a href="phpenhancements.php">PHP Enchancements</a>
            <a href="quiz.php">Quiz</a>
            <a href="loginform.php">Manage Quiz Queries</a>
        </nav>

        <div class="link_wrapper">
            <a href="https://github.com/DannyOCE/inquiry-project">
                <img src="images/github_logo.png" class="github_logo" alt="github logo">
            </a>
        </div>
</header>