 <footer>

        <p class="completed_by">
            Project completed by:
            <br><br>
            <strong><a href=mailto:103968787@student.swin.edu.au>Adam</a>, <a href=mailto:103986527@student.swin.edu.au>Daniel</a>, <a href=mailto:104004035@student.swin.edu.au>Alister</a>, <a href=mailto:103988235@student.swin.edu.au>Sam G</a>, <a href=mailto:103999745@student.swin.edu.au>Sam S</a></strong>
        </p>

</footer>