

<div class="manage-container">
<h3 class="subheader"></h3>
        <form method="post" action="index.php" >
                <p>
                    <input type="submit" value="Continue to Index page">
                </p>
        </form>
    <h3 class="subheader"></h3>
        <form method="post" action="loginform.php" >
                <p>
                    <input type="submit" value="Continue to Manage Quiz Queries">
                </p>
        </form>
    <h3 class="subheader"></h3>
        <form method="post" action="quiz.php" >
                <p>
                    <input type="submit" value="Retake the test">
                </p>
        </form>
</div>