<div class="manage-container">
<h3 class="subheader">Continue to Index page</h3>
        <form method="post" action="index.php" >
                <p>
                    <input type="submit" >
                </p>
        </form>
    <h3 class="subheader">Continue to Manage Quiz Queries</h3>
        <form method="post" action="manage.php" >
                <p>
                    <input type="submit" >
                </p>
        </form>
    <h3 class="subheader">Retake the test</h3>
        <form method="post" action="quiz.php" >
                <p>
                    <input type="submit" >
                </p>
        </form>
</div>