<div class="manage-container">
<h3 class="subheader"></h3>
        <form method="post" action="index.php" >
                <p>
                    <input type="submit" name="Continue to Index page">
                </p>
        </form>
    <h3 class="subheader"></h3>
        <form method="post" action="manage.php" >
                <p>
                    <input type="submit" name="Continue to Manage Quiz Queries">
                </p>
        </form>
    <h3 class="subheader"></h3>
        <form method="post" action="quiz.php" >
                <p>
                    <input type="submit" name="Retake the test">
                </p>
        </form>
</div>