 <footer>

        <p id="footnotes">
            <!-- Text References -->
            <strong>References</strong>
            <br><br>
            <a id="node" href="https://www.w3schools.com/nodejs/nodejs_intro.asp">https://www.w3schools.com/nodejs/nodejs_intro.asp</a><sub>[1] [6]</sub>
            <br>
            <a id="js1" href="https://www.youtube.com/watch?v=uVwtVBpw7RQ">https://www.youtube.com/watch?v=uVwtVBpw7RQ</a><sub>[5]</sub>
            <br>
            <a id="cr" href="http://www.h-online.com/open/features/The-H-Speed-Guide-to-Node-js-1363974.html%3Fpage=2">http://www.h-online.com/open/features/The-H-Speed-Guide-to-Node-js-1363974.html%3Fpage=2</a><sub>[7]</sub>
            <br>
            <a id="node_rise" href="https://www.peerbits.com/blog/rise-of-node-js-for-enterprise-app-development.html">https://www.peerbits.com/blog/rise-of-node-js-for-enterprise-app-development.html</a><sub>[3] [4] [9] [10] [11]</sub>
            <br>
            <a id="php1" href="https://www.w3schools.com/php/php_intro.asp">https://www.w3schools.com/php/php_intro.asp</a><sub>[23]</sub>
            <br>
            <a id="asp1" href="https://www.w3schools.com/asp/asp_introduction.asp">https://www.w3schools.com/asp/asp_introduction.asp</a><sub>[18]</sub>
            <br>
            <a id="vs" href="https://www.outsystems.com/blog/posts/asynchronous-vs-synchronous-programming/">https://www.outsystems.com/blog/posts/asynchronous-vs-synchronous-programming/</a><sub>[19] [25]</sub>
            <br>
            <a id="b_e" href="https://dictionary.cambridge.org/dictionary/english/back-end">https://dictionary.cambridge.org/dictionary/english/back-end</a><sub>[20]</sub>
            <br>
            <a id="rt" href="https://dictionary.cambridge.org/dictionary/english/run-time?q=runtime">https://dictionary.cambridge.org/dictionary/english/run-time?q=runtime</a><sub>[21]</sub>
            <br>
            <a id="sim" href="https://www.simform.com/blog/companies-using-nodejs/">https://www.simform.com/blog/companies-using-nodejs/</a><sub>[12]</sub>
            <br>
            <a id="elixir" href="https://elixir-lang.org">https://elixir-lang.org</a><sub>[13]</sub>
            <br>
            <a id="perl" href="https://www.simplilearn.com/perl-programming-for-beginners-article">https://www.simplilearn.com/perl-programming-for-beginners-article</a><sub>[14]</sub>
            <br>
            <a id="reb" href="http://www.rebol.com">http://www.rebol.com</a><sub>[15]</sub>
            <br>
            <a id="asp2" href="https://www.wakefly.com/blog/what-is-asp-net-and-why-should-i-use-it/">https://www.wakefly.com/blog/what-is-asp-net-and-why-should-i-use-it/</a><sub>[16]</sub>
            <br>
            <a id="gov" href="https://nodejs.org/en/about/governance/">https://nodejs.org/en/about/governance/</a><sub>[8]</sub>
            <br>
            <a id="pros_cons" href="https://railsware.com/blog/what-is-node-js-used-for/#Pros_Cons">https://railsware.com/blog/what-is-node-js-used-for/#Pros_Cons</a><sub>[2]</sub>
            <br>
            <a id="para" href="https://www.computerhope.com/jargon/p/parallelization.htm">https://www.computerhope.com/jargon/p/parallelization.htm</a><sub>[22]</sub>
            <br>
            <a id="api1" href="https://www.mulesoft.com/resources/api/what-is-an-api#:~:text=API%20is%20the%20acronym%20for,you're%20using%20an%20API.">https://www.mulesoft.com/resources/api/what-is-an-api#:~:text=API%20is%20the%20acronym%20for,you're%20using%20an%20API.</a><sub>[17]</sub>
            <br>
            <a id="js2" href="https://www.analyticsinsight.net/best-programming-languages-for-web-development/">https://www.analyticsinsight.net/best-programming-languages-for-web-development/</a><sub>[21]</sub>
            <br>
            <a id="otherpage1" href="https://mindmajix.com/node-js/node-basic-examples">https://mindmajix.com/node-js/node-basic-examples</a><sub>[Index page references]</sub>
            <br>
            <a id="otherpage2" href="https://www.the-guild.dev/blog/support-nodejs-esm">https://www.the-guild.dev/blog/support-nodejs-esm</a><sub>[Index page references]</sub>
            <br>
            <a id="otherpage3" href="https://nodejs.org/en/about/">https://nodejs.org/en/about/</a><sub>[Index page references]</sub>
            <br>
            <a id="otherpage4" href="https://www.youtube.com/watch?v=8u1o-OmOeGQ">https://www.youtube.com/watch?v=8u1o-OmOeGQ</a><sub>[Index page references]</sub>
            <br>
            <!-- HTML Code References -->   
            <a id="otherpage5" href="https://stackoverflow.com/questions/20565644/how-to-link-to-a-div-on-another-page">https://stackoverflow.com/questions/20565644/how-to-link-to-a-div-on-another-page</a><sub>[26]</sub>
            <br>
            <!-- Add an icon to the webpage  (topic.html line 13) -->
            <a href="https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website">https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website</a>
            <!-- CSS Code References -->
            <!-- Changes numbers/points in lists to different colors (topic.css lines 132-142 & 251-262)-->
            <a href="https://www.w3.org/Style/Examples/007/color-bullets.en.html ">https://www.w3.org/Style/Examples/007/color-bullets.en.html</a>
            <br>
            <!-- Removes cell spacing/padding between table contents  (topic.css lines 186-189)-->
            <a href="https://stackoverflow.com/questions/16427903/remove-all-padding-and-margin-table-html-and-css">https://stackoverflow.com/questions/16427903/remove-all-padding-and-margin-table-html-and-css</a>
        </p>
        <br>
        <p class="completed_by">
            Project completed by:
            <br><br>
            <strong><a href=mailto:103968787@student.swin.edu.au>Adam</a>, <a href=mailto:103986527@student.swin.edu.au>Daniel</a>, <a href=mailto:104004035@student.swin.edu.au>Alister</a>, <a href=mailto:103988235@student.swin.edu.au>Sam G</a>, <a href=mailto:103999745@student.swin.edu.au>Sam S</a></strong>
        </p>

</footer>